# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SABR
email: SABR-1331@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
 SABR - is an open source cryptocurrency for a real business
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://SABR-1331.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  SABR-1331

# Build settings
markdown: kramdown